---
driver:
  name: docker
  use_sudo: false

transport:
  max_ssh_sessions: 6  
  
provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: roles
  ansible_verbosity: 5 
  ansible_verbose: true
  ansible_sudo: true
  require_ansible_repo: false 
  require_ansible_omnibus: false
  require_ansible_source: true
  require_chef_for_busser: false

platforms:
#  - name: ubuntu-16.10
  - name: centos-7
    driver_config: 
        image: centos:7
        provision_command: yum install -y python python-yaml python-jinja2
        platform: centos
verifier:
  name: serverspec

suites:
    - name: default
      provisioner:
          name: ansible_playbook
          playbook: roles/test/integration/default/default.yml
      verifier:
         patterns:
           - roles/test/integration/default/serverspec/default_spec.rb
