---
driver:
  name: docker
  use_sudo: false

transport:
  max_ssh_sessions: 6  
  
provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: roles
  ansible_verbosity: 3
  ansible_verbose: false
  require_ansible_repo: true 
  require_ansible_omnibus: false
  require_chef_for_busser: false

platforms:
  - name: ubuntu-14.04

verifier:
  name: serverspec

suites:
    - name: default
      provisioner:
          name: ansible_playbook
          playbook: roles/test/integration/default/default.yml
      verifier:
         patterns:
           - roles/test/integration/default/serverspec/default_spec.rb
