# roles/devops/tasks/ssh-config.yaml
---
- name: 1. Create ~/.ssh directory
  file:
      path: "{{ local_user_home }}/.ssh"
      mode: 0700
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      state: directory
- name: 2. Copy private cert
  copy:
      dest: "{{ local_user_home }}/.ssh/homelab_rsa"
      src: ../files/homelab_rsa
      mode: 0600
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
- name: 3+ Copy public cert
  copy:
      src: ../files/homelab_rsa.pub
      dest: "{{ local_user_home }}/.ssh/homelab_rsa.pub"
      mode: 0600
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
- name: 3. Copy ssh config file
  template:
      src: "../templates/ssh_config.j2"
      dest: "{{ local_user_home }}/.ssh/config"
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
